services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - app-network
      - easypanel-hhb # Connect to Easypanel's network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hhb-frontend.rule=Host(`hhb-offers.q5l76g.easypanel.host`)"
      - "traefik.http.services.hhb-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.hhb-frontend.entrypoints=websecure"
      - "traefik.http.routers.hhb-frontend.tls=true"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=direct_mail_db
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=direct_mail_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
  easypanel-hhb:
    external: true
