services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=direct_mail_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - redis
      - postgres
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_net

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=direct_mail_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - app_net

volumes:
  redis_data:
  postgres_data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
