services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=direct_mail_db
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - JWT_SECRET=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis
      - postgres
    networks:
      - easypanel-mail

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - easypanel-mail

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=direct_mail_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - easypanel-mail

volumes:
  redis_data:
  postgres_data:

# networks:
#   easypanel-mail:
#     driver: overlay
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16

networks:
  easypanel-mail:
    driver: bridge
