"""Initial database schema

Revision ID: 0001
Revises:
Create Date: 2024-05-16 10:00:00.000000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('property_address', sa.String(length=255), nullable=False),
    sa.Column('property_city', sa.String(length=100), nullable=False),
    sa.Column('property_state', sa.String(length=2), nullable=False),
    sa.Column('property_zip', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_address', 'property_city', 'property_state', 'property_zip', name='idx_property_unique')
    )
    op.create_index('idx_properties_address', 'properties', ['property_address'], unique=False)
    op.create_index('idx_properties_address_full', 'properties', ['property_address', 'property_city', 'property_state', 'property_zip'], unique=False)
    op.create_index('idx_properties_city', 'properties', ['property_city'], unique=False)
    op.create_index('idx_properties_last_name', 'properties', ['last_name'], unique=False)
    op.create_index('idx_properties_state', 'properties', ['property_state'], unique=False)

    op.create_table('offer_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('offer_amount', sa.Text(), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_offer_history_date', 'offer_histories', ['offer_date'], unique=False)
    op.create_index('idx_offer_history_property', 'offer_histories', ['property_id'], unique=False)

    op.create_table('upload_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('new_records', sa.Integer(), nullable=True),
    sa.Column('updated_records', sa.Integer(), nullable=True),
    sa.Column('error_records', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_jobs_status', 'upload_jobs', ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_activity_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_logs_entity', table_name='audit_logs')
    op.drop_index('idx_activity_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_activity_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')

    op.drop_index('idx_upload_jobs_status', table_name='upload_jobs')
    op.drop_table('upload_jobs')

    op.drop_index('idx_offer_history_property', table_name='offer_histories')
    op.drop_index('idx_offer_history_date', table_name='offer_histories')
    op.drop_table('offer_histories')

    op.drop_index('idx_properties_state', table_name='properties')
    op.drop_index('idx_properties_last_name', table_name='properties')
    op.drop_index('idx_properties_city', table_name='properties')
    op.drop_index('idx_properties_address_full', table_name='properties')
    op.drop_index('idx_properties_address', table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
